### ISSUE TITLE
Error with command "clues shownode <node_name>"

### ISSUE THREAD

**Issue by amcaar** [grycap/clues#5]
Hi,

the command "clues shownode _node_name_" is causing the next error:

```
ubuntu@slurmserverpublic:~$ clues shownode wn1
WARNING: Couldn't write lextab module 'lextab'. [Errno 20] Not a directory: '/usr/local/lib/python2.7/dist-packages/cpyutils-0.24-py2.7.egg/cpyutils/lextab.py'
WARNING: Couldn't create 'parsetab'. [Errno 20] Not a directory: '/usr/local/lib/python2.7/dist-packages/cpyutils-0.24-py2.7.egg/cpyutils/parsetab.py'
Traceback (most recent call last):
File "/usr/local/bin/clues", line 222, in <module>
main_function()
File "/usr/local/bin/clues", line 219, in main_function
p.self_service(True)
File "build/bdist.linux-x86_64/egg/cpyutils/parameters.py", line 501, in self_service
File "build/bdist.linux-x86_64/egg/cpyutils/parameters.py", line 479, in autocall_ops
File "/usr/local/bin/clues", line 115, in shownode
node = Node.fromxml(Node("",0,0,0,0), text)
File "/usr/local/lib/python2.7/dist-packages/clueslib/helpers.py", line 186, in fromxml
reference_object.dict[v] = int(n.dict[v])
ValueError: invalid literal for int() with base 10: '1073741824.0'
```

Any idea of what's happening there? Thank you in advance.

**Comment by dealfonso** [comment]
commit #67db845 seems solves this problem
