### ISSUE TITLE
KeyError: ‘MinMemoryNode' in SLURM plugin

### ISSUE THREAD

**Issue by micafer** [grycap/clues#73]
```
Traceback (most recent call last):
  File "/bin/cluesserver", line 618, in <module>
    main_loop()
  File "/bin/cluesserver", line 615, in main_loop
    CLUES_DAEMON.loop(options.RT_MODE)
  File "/usr/lib/python2.7/site-packages/clueslib/cluesd.py", line 604, in loop
    cpyutils.eventloop.get_eventloop().loop()
  File "build/bdist.linux-x86_64/egg/cpyutils/eventloop.py", line 299, in loop
  File "build/bdist.linux-x86_64/egg/cpyutils/eventloop.py", line 138, in call
  File "build/bdist.linux-x86_64/egg/cpyutils/eventloop.py", line 101, in call
  File "/usr/lib/python2.7/site-packages/clueslib/cluesd.py", line 382, in _monitor_lrms_nodes_and_jobs
    self._monitor_lrms_jobs()
  File "/usr/lib/python2.7/site-packages/clueslib/cluesd.py", line 332, in _monitor_lrms_jobs
    lrms_jobinfolist = self._platform.get_jobinfolist()
  File "/usr/lib/python2.7/site-packages/clueslib/platform.py", line 50, in get_jobinfolist
    return self._lrms.get_jobinfolist()
  File "/usr/lib/python2.7/site-packages/cluesplugins/slurm.py", line 280, in get_jobinfolist
    memory = _translate_mem_value(job["MinMemoryNode"] + ".MB")
KeyError: ‘MinMemoryNode'
```

**Comment by micafer** [comment]
Issue reported by @mtangaro.
